---
### PATHS

## Reference Files
bed_file: /data/static_libraries/RefGene/refseqGenesHg19.bed
gtf_file: /home/lentaing/tmp/weinstock/newrun/ref_files/Hg19_CTAT_resource_lib/ref_annot.gtf
ref_fasta: /data/static_libraries/assembly/humanhg19/rawgenome/hg19.fasta
star_index: /data/static_libraries/STAR/humanhg19/
star_rRNA_index: /home/lentaing/tmp/weinstock/newrun/ref_files/humanhg38_ncrna/
reference: hg19

## STAR fusion
genome_lib_dir: /home/lentaing/tmp/weinstock/newrun/ref_files/Hg19_CTAT_resource_lib

## Metasheet location. If you change the name of your metasheet or its location from where you are running VIPER from, you must change it here.
metasheet: metasheet.csv

## Hardcoded local packages
python2: /usr/bin/python2.7
picard_path: /home/lentaing/setup_files/picard-tools-1.115
rseqc_path: /usr/local/bin

#possible values are, true and false
stranded: true
# if stranded true, library_type is a required argument
# Possible values are [ff-firststrand, ff-secondstrand, ff-unstranded, fr-firststrand, fr-secondstrand, fr-unstranded (default), transfrags]
library_type: fr-firststrand

# Varscan
varscan_jar_path: /home/lentaing/setup_files/varscan-master/VarScan.v2.4.1.jar
# Turn on the following if you want a genome wide snp scan in addition to chr6 scan
# possible value are ["true","false"]
snp_scan_genome: "false"

# file that is generated by gtf2annot.R--human and mouse annotations found in
# static/ dir-- use bzip2 -d humanhg19.annot.csv.bz2
gene_annotation: viper/static/humanhg19.annot.csv



###PARAMS

# Data filtering parameters
RPKM_threshold: "1.0"
min_num_samples_expressing_at_threshold: "1"
filter_mirna: "TRUE"

# Number of genes in heatmaps
SSnumgenes: "250"
SFnumgenes: "1000"

# Parameter for type of SF heatmap to generate. "0" yields a hierarchical, "2","3","4",... yields a kmeans clustering.
# "4,0,5" will yield a 4 kmeans clustered, a hierarchical and a 5 kmeans clustered
num_kmeans_clust: "2"

### SAMPLES

samples:
    IRJ57:
        - /mnt/cfce-stor1/data/port/20160123_mbcf/160122_MP2683_NS500233_fastq/20160122-IRJ57-MP2683_S19_R1_001.fastq.gz
    IRJ60:
        - /mnt/cfce-stor1/data/port/20160123_mbcf/160122_MP2683_NS500233_fastq/20160122-IRJ60-MP2683_S20_R1_001.fastq.gz
    IRJ63:
        - /mnt/cfce-stor1/data/port/20160123_mbcf/160122_MP2683_NS500233_fastq/20160122-IRJ63-MP2683_S21_R1_001.fastq.gz
    IRJ66:
        - /mnt/cfce-stor1/data/port/20160123_mbcf/160122_MP2683_NS500233_fastq/20160122-IRJ66-MP2683_S22_R1_001.fastq.gz
    IRJ69:
        - /mnt/cfce-stor1/data/port/20160123_mbcf/160122_MP2683_NS500233_fastq/20160122-IRJ69-MP2683_S23_R1_001.fastq.gz
    IRJ72:
        - /mnt/cfce-stor1/data/port/20160123_mbcf/160122_MP2683_NS500233_fastq/20160122-IRJ72-MP2683_S24_R1_001.fastq.gz
    IRJ56:
        - /mnt/cfce-stor1/data/port/20160129_mbcf/160128_MP2689_NS500144_fastq/20160128-IRJ56-MP2689_S19_R1_001.fastq.gz
    IRJ59:
        - /mnt/cfce-stor1/data/port/20160129_mbcf/160128_MP2689_NS500144_fastq/20160128-IRJ59-MP2689_S20_R1_001.fastq.gz
    IRJ62:
        - /mnt/cfce-stor1/data/port/20160129_mbcf/160128_MP2689_NS500144_fastq/20160128-IRJ62-MP2689_S21_R1_001.fastq.gz
    IRJ65:
        - /mnt/cfce-stor1/data/port/20160129_mbcf/160128_MP2689_NS500144_fastq/20160128-IRJ65-MP2689_S22_R1_001.fastq.gz
    IRJ68:
        - /mnt/cfce-stor1/data/port/20160129_mbcf/160128_MP2689_NS500144_fastq/20160128-IRJ68-MP2689_S23_R1_001.fastq.gz
    IRJ71:
        - /mnt/cfce-stor1/data/port/20160129_mbcf/160128_MP2689_NS500144_fastq/20160128-IRJ71-MP2689_S24_R1_001.fastq.gz
    IRJ55:
        - /mnt/cfce-stor1/data/port/20160207_mbcf/160125_MP2688_NS500144_fastq/20160125-IRJ55-MP2688_S19_R1_001.fastq.gz
    IRJ58:
        - /mnt/cfce-stor1/data/port/20160207_mbcf/160125_MP2688_NS500144_fastq/20160125-IRJ58-MP2688_S20_R1_001.fastq.gz
    IRJ61:
        - /mnt/cfce-stor1/data/port/20160207_mbcf/160125_MP2688_NS500144_fastq/20160125-IRJ61-MP2688_S21_R1_001.fastq.gz
    IRJ64:
        - /mnt/cfce-stor1/data/port/20160207_mbcf/160125_MP2688_NS500144_fastq/20160125-IRJ64-MP2688_S22_R1_001.fastq.gz
    IRJ67:
        - /mnt/cfce-stor1/data/port/20160207_mbcf/160125_MP2688_NS500144_fastq/20160125-IRJ67-MP2688_S23_R1_001.fastq.gz
    IRJ70:
        - /mnt/cfce-stor1/data/port/20160207_mbcf/160125_MP2688_NS500144_fastq/20160125-IRJ70-MP2688_S24_R1_001.fastq.gz